apiVersion: apps/v1
kind: Deployment
metadata:
  name:  demo-deployment
  namespace: default
  labels:
    app:  demo-deployment
spec:
  selector:
    matchLabels:
      app: demo-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app:  demo-deployment
    spec:
      containers:
      - name:  web
        image:  azureday.azurecr.io/azureday-web:848dcda26c494ffe335d88791afd575951be970d
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  demo-deployment
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: default
spec:
  selector:
    app: demo-deployment
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
