apiVersion: apps/v1
kind: Deployment
metadata:
  name:  demo-deployment
  namespace: default
  labels:
    app:  demo-deployment
spec:
  selector:
    matchLabels:
      app: demo-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app:  demo-deployment
    spec:
      containers:
      - name:  web
        image:  "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  demo-deployment
      restartPolicy: Always