on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build
      - run: dotnet test

  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to docker registry
        uses: docker/login-action@v1 
        with:
          registry: azureday.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azureday.azurecr.io/azureday-web:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [docker]
    steps: 
      - uses: actions/checkout@v2
      - name: Configure K8s context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - run: helm upgrade azureday helm/ --set image.tag=${{ github.sha }} --install